spring:
  application:
    name: history-api

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/candles}
    username: ${DB_USER:candle}
    password: ${DB_PASS:candle}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

server:
  port: 8083

logging:
  level:
    com.candle: INFO
